name: Deploy FastAPI App to Render

on:
  push:
    branches: [main]  # Deploys when code is pushed to the main branch
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cv1gqb5ds78s73drvqp0?key=a-eZBdHhY5I"
